/**
 * Extract YouTube/Google cookies from Chrome on Windows.
 * Works around yt-dlp DPAPI failures (yt-dlp#10927) by decrypting ourselves.
 * Writes Netscape cookies.txt for yt-dlp --cookies.
 */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { DatabaseSync } from 'node:sqlite';

function chromeUserData() {
  const local = process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local');
  return path.join(local, 'Google', 'Chrome', 'User Data');
}

function decryptDpapi(base64) {
  const raw = Buffer.from(String(base64), 'base64');
  const payload = raw.subarray(5); // skip "DPAPI"
  const tmpIn = path.join(os.tmpdir(), `pm-dpapi-in-${process.pid}.bin`);
  const tmpOut = path.join(os.tmpdir(), `pm-dpapi-out-${process.pid}.bin`);
  fs.writeFileSync(tmpIn, payload);
  const ps = [
    'Add-Type -AssemblyName System.Security',
    `$b = [IO.File]::ReadAllBytes('${tmpIn.replace(/'/g, "''")}')`,
    `$p = [Security.Cryptography.ProtectedData]::Unprotect($b, $null, 'CurrentUser')`,
    `[IO.File]::WriteAllBytes('${tmpOut.replace(/'/g, "''")}', $p)`,
  ].join('; ');
  try {
    execFileSync('powershell', ['-NoProfile', '-NonInteractive', '-Command', ps], {
      windowsHide: true,
    });
    return fs.readFileSync(tmpOut);
  } finally {
    fs.rmSync(tmpIn, { force: true });
    fs.rmSync(tmpOut, { force: true });
  }
}

function decryptCookieValue(value, key) {
  if (!value || value.length < 3) return null;
  const prefix = value.subarray(0, 3).toString('utf8');
  if (prefix !== 'v10' && prefix !== 'v11') return value.toString('utf8');
  if (value.length < 3 + 12 + 16) return null;
  const nonce = value.subarray(3, 15);
  const ciphertext = value.subarray(15, value.length - 16);
  const tag = value.subarray(value.length - 16);
  try {
    const decipher = crypto.createDecipheriv('aes-256-gcm', key, nonce);
    decipher.setAuthTag(tag);
    return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString('utf8');
  } catch {
    return null;
  }
}

function copyWithRetry(src, dest, tries = 8) {
  for (let i = 0; i < tries; i++) {
    try {
      fs.copyFileSync(src, dest);
      return true;
    } catch {
      const t0 = Date.now();
      while (Date.now() - t0 < 30) {
        /* spin */
      }
    }
  }
  return false;
}

function listProfiles(userData) {
  const wanted = ['Default', 'Profile 1', 'Profile 2', 'Profile 3', 'Profile 4'];
  return wanted.filter((p) => {
    return (
      fs.existsSync(path.join(userData, p, 'Network', 'Cookies')) ||
      fs.existsSync(path.join(userData, p, 'Cookies'))
    );
  });
}

export function extractChromeYoutubeCookies() {
  const userData = chromeUserData();
  const localStatePath = path.join(userData, 'Local State');
  if (!fs.existsSync(localStatePath)) {
    throw new Error('Chrome is not installed (User Data missing)');
  }
  const localState = JSON.parse(fs.readFileSync(localStatePath, 'utf8'));
  const encKey = localState?.os_crypt?.encrypted_key;
  if (!encKey) throw new Error('Chrome encryption key missing');
  const aesKey = decryptDpapi(encKey);

  const lines = ['# Netscape HTTP Cookie File', '# generated by pouya-music', ''];
  let found = 0;

  for (const profile of listProfiles(userData)) {
    const src =
      [
        path.join(userData, profile, 'Network', 'Cookies'),
        path.join(userData, profile, 'Cookies'),
      ].find((p) => fs.existsSync(p)) || null;
    if (!src) continue;
    const tmp = path.join(os.tmpdir(), `pm-ck-${profile.replace(/\W/g, '')}-${process.pid}.db`);
    if (!copyWithRetry(src, tmp)) {
      throw new Error(
        'Chrome is locking its cookie database. Close Google Chrome completely, then retry.'
      );
    }
    let db;
    try {
      db = new DatabaseSync(tmp, { readOnly: true });
      const rows = db
        .prepare(
          `SELECT host_key, name, encrypted_value, path, CAST(expires_utc AS TEXT) AS expires_utc, is_secure
             FROM cookies
            WHERE host_key LIKE '%.youtube.com'
               OR host_key LIKE '%.google.com'
               OR host_key LIKE '%.googlevideo.com'
               OR host_key = 'youtube.com'`
        )
        .all();
      for (const row of rows) {
        const value = decryptCookieValue(Buffer.from(row.encrypted_value), aesKey);
        if (value == null || value === '') continue;
        // Netscape cookies.txt cannot contain raw tabs/newlines in values.
        // Skip AEC/other high-entropy binary cookies; keep auth cookies.
        if (/[\t\r\n]/.test(value)) continue;
        const name = String(row.name);
        const keepNames =
          /^(SID|HSID|SSID|APISID|SAPISID|NID|__Secure-1PSID|__Secure-3PSID|__Secure-1PAPISID|__Secure-3PAPISID|__Secure-1PSIDTS|__Secure-3PSIDTS|SIDCC|__Secure-1PSIDCC|__Secure-3PSIDCC)$/;
        if (!keepNames.test(name) && !/^(SID|HSID|SSID|APISID|SAPISID)/.test(name)) {
          // still allow other simple printable values
          if (!/^[\x20-\x7E]+$/.test(value)) continue;
        }
        let expires = 0;
        try {
          const eu = BigInt(row.expires_utc ?? 0);
          if (eu > 0n) {
            const sec = eu / 1_000_000n - 11_644_473_600n;
            expires = sec > 0n && sec < 2_000_000_000n ? Number(sec) : 0;
          }
        } catch {
          expires = 0;
        }
        const secure = row.is_secure ? 'TRUE' : 'FALSE';
        const includeSub = String(row.host_key).startsWith('.') ? 'TRUE' : 'FALSE';
        lines.push(
          [
            row.host_key,
            includeSub,
            row.path || '/',
            secure,
            expires,
            row.name,
            value,
          ].join('\t')
        );
        found++;
      }
      db.close();
    } catch (e) {
      if (db) {
        try {
          db.close();
        } catch {
          /* ignore */
        }
      }
      fs.rmSync(tmp, { force: true });
      throw e;
    }
    fs.rmSync(tmp, { force: true });
  }

  if (found === 0) {
    throw new Error(
      'No YouTube cookies decrypted. Sign into youtube.com in Chrome, or import cookies.txt.'
    );
  }
  return lines.join('\n') + '\n';
}

export function writeCookiesFile(dest) {
  const text = extractChromeYoutubeCookies();
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, text, 'utf8');
  return { dest, bytes: Buffer.byteLength(text), lines: text.split('\n').length };
}

// CLI: node chromeCookies.mjs [outfile]
if (process.argv[1] && process.argv[1].endsWith('chromeCookies.mjs')) {
  const dest =
    process.argv[2] ||
    path.join(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), 'cookies-live.txt');
  try {
    const info = writeCookiesFile(dest);
    console.log('wrote', info.dest, 'bytes', info.bytes);
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}
